version: "3.8"
services:
  app:
    build: .
    environment:
      - HOST=0.0.0.0
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./:/app:cached
    ports:
      - "3000:3000"
      - "24678:24678"
    tty: true
